# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeltExam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_users',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='LoginAndReg.User'),
        ),
        migrations.AlterField(
            model_name='trip_users',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_users', to='BeltExam.Trip'),
        ),
    ]
